//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeriPark.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryConfiguration
    {
        public int Id { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public string FreeDay { get; set; }
        public string PublicHoliday { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
